"""add color to kanban_columns

Revision ID: 0bb06ef10312
Revises: 2e963752a502
Create Date: 2026-05-30 04:53:16.919760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb06ef10312'
down_revision: Union[str, Sequence[str], None] = '2e963752a502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanban_columns', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanban_columns', 'color')
    # ### end Alembic commands ###
